# Generated by Django 3.2 on 2021-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210408_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recipe',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
    ]
