# Generated by Django 3.2 on 2021-04-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='hasQuantity',
            field=models.BooleanField(default=True, null=True, verbose_name='Содержит количество'),
        ),
    ]
