# Generated by Django 3.2 on 2021-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeComposition', to='recipes.Ingredient', verbose_name='Тэги'),
        ),
    ]
