# Generated by Django 3.2 on 2021-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_tag_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recipe',
            field=models.ManyToManyField(blank=True, related_name='tags', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
    ]
